### Get all policemans

GET http://localhost:8080/api/policemans

### Get policeman by id

GET http://localhost:8080/api/policemans/234a2578-d792-448a-97eb-a2a8c27c913d

### Update policeman

PUT http://localhost:8080/api/policemans/234a2578-d792-448a-97eb-a2a8c27c913d
Content-Type: application/json

{
    "name": "Policeman Update",
    "rank": 57
}

### Delete policeman

DELETE http://localhost:8080/api/policemans/234a2578-d792-448a-97eb-a2a8c27c913d





### Get all tickets

GET http://localhost:8080/api/tickets

### Get ticket by id

GET http://localhost:8080/api/tickets/87621c46-8b38-4bc9-a13c-a353a0dd6121

### Update ticket

PUT http://localhost:8080/api/tickets/87621c46-8b38-4bc9-a13c-a353a0dd6121
Content-Type: application/json

{
    "policeman": "4b695da9-2141-40d8-9cfa-8212f81be2aa",
    "reason": "Ticket Update Reasoning",
    "price": 9090
}

### Delete ticket

DELETE http://localhost:8080/api/tickets/87621c46-8b38-4bc9-a13c-a353a0dd6121

